GET http://dou.imoosoo.net:8888/chat_list?seller_id=dou_imoosoo_net&keyword=1234
Accept: application/json

###
GET http://192.168.0.189:8888/chat_list?seller_id=abc
Accept: application/json

###
GET http://192.168.0.189:8888/chat_history?seller_id=abc&buyer_id=862c6fb801865dea1364e5d0baa7b8a3

###
POST http://192.168.0.189:8888/buyer
Accept: application/json

{"buyer_id": "ab3074f95927e5981712073c1e7234d7", "name": "noodles", "email": "noodles@noodles.com", "seller_id": "dou_imoosoo_net"}

###
GET http://192.168.0.189:8888/buyer?seller_id=dou_imoosoo_net&buyer_id=ab3074f95927e5981712073c1e7234d7

###
